### ISSUE TITLE
Tracking issue of Keyboard DataProcessor

### ISSUE THREAD

**Issue by yuvalkh** [capi-bgu/capi#8]
Implement Keyboard data processor that will make features and clean data.

**Comment by hodTwito** [comment]
The features we decided to implement:

- [x] typing_speed
- [x] active_typing_speed
- [x] average_press_duration
- [x] average_down_to_down
- [x] regular_press_count
- [x] punctuations_press_count
- [x] space_countern
- [x] error_corrections
- [x] uppercase_counter
- [x] mode_key
- [x] idle_time
- [x] unique_events
