### ISSUE TITLE
Tracking issue of Mouse DataProcessor

### ISSUE THREAD

**Issue by yuvalkh** [capi-bgu/capi#9]
Implement mouse data processor that will make features and clean data.

**Comment by hodTwito** [comment]
The features we decided to implement:

- [x] right_click_count
- [x] left_click_count
- [x] scroll_speed
- [x] double_click_count
- [x] cursor_x_distance
- [x] cursor_y_distance
- [x] average_momentary_speed
- [x] average_momentary_speed
- [x] average_speed_x
- [x] average_speed_y
- [x] average_active_speed_x
- [x] average_active_speed_y
- [x] average_cursor_angle
- [x] std_cursor_angle
- [x] Turn_0_45
- [x] Turn_45_90
- [x] Turn_90_135
- [x] Turn_135_180
- [x] Direction_S
- [x] Direction_SW
- [x] Direction_W
- [x] Direction_NW
- [x] Direction_N
- [x] Direction_NE
- [x] Direction_E
- [x] Direction_SE
- [x] Dist1
- [x] Dist2
- [x] Dist3
- [x] idle_time
- [x] right_click_duration
- [x] left_click_duration
